name: Publish on Merge

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed bootc images
        id: changed-dirs
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          files: |
            **/bootc/**
          matrix: true

      - name: Set output in matrix format
        id: set-output
        run: |
          dirs='${{ steps.changed-dirs.outputs.all_changed_files }}'
          # Extract parent directory of bootc/ (e.g., centos-bootc from base/centos-bootc/bootc)
          dirs=$(echo "${dirs}" | jq -c 'map(split("/bootc") | .[0] | split("/") | .[-1])')
          echo "changed_images=${dirs}"
          echo "changed_images=${dirs}" >> "$GITHUB_OUTPUT"

    outputs:
      images: ${{ steps.set-output.outputs.changed_images }}


  build-bootc-images:
    needs: [detect-changes]

    if: ${{ needs.detect-changes.outputs.images != '[]' }}

    strategy:
      matrix:
        image: ${{ fromJSON(needs.detect-changes.outputs.images) }}
      max-parallel: 4
      fail-fast: false

    uses: ./.github/workflows/build-bootc-image.yaml
    with:
      demo: ${{ matrix.image }}
      oci-registry: quay.io
      oci-org: flightctl-demos
      tags: latest,${{ github.sha }}
      dry_run: false
    secrets: inherit


  build-disk-images:
    needs: [detect-changes, build-bootc-images]

    if: ${{ needs.detect-changes.outputs.images != '[]' }}

    strategy:
      matrix:
        image: ${{ fromJSON(needs.detect-changes.outputs.images) }}
      max-parallel: 4
      fail-fast: false

    uses: ./.github/workflows/build-bootc-diskimage.yaml
    with:
      demo: ${{ matrix.image }}
      oci-registry: quay.io
      oci-org: flightctl-demos
      tags: latest,${{ github.sha }}
    secrets: inherit
